"""removed the comma 

Revision ID: cb92a304129f
Revises: 9862a4a8f960
Create Date: 2025-03-05 15:43:59.438251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb92a304129f'
down_revision: Union[str, None] = '9862a4a8f960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profiles', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'student_id')
    # ### end Alembic commands ###
